### ISSUE TITLE
自機を動かす機能

### ISSUE THREAD

**Issue by EikiOta** [EikiOta/SignalOfSpace#3]

**Comment by EikiOta** [comment]
<h1>自機を動かす機能</h1>

### 概要
プレイヤーがキーボードで矢印キーを入力して、それに沿って自分の機体が移動できるようにする

### ユーザストーリー
プレイヤーは矢印キーを押して任意の方向に機体を動かす。
-> スピードは？加速は？

**Comment by Hiroki-5224** [comment]
こんにちは
